# Generated by Django 3.0.7 on 2020-06-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=256, unique=True)),
                ('more_info', models.URLField(unique=True)),
                ('company_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_app.Company')),
            ],
        ),
    ]
